name: Build Componrnt

on:

  push:

    branches: [ '*' ]

  pull_request:

    branches: [ '*' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js

        uses: actions/setup-node@v2

        with:

          node-version: '18.x'

      - name: Install dependencies

        run: npm i

      - name: Build package

        run: npm run fmt && npm run build
